import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { STEP6_FILES, STEP_DIRS } from "./constants.js";
import { copyDirectory } from "./fs-utils.js";
import { validateSafeDirectoryName } from "./name-validation.js";
import { resolveRepoRoot } from "./paths.js";
import { syncProject } from "./sync.js";
import type { CreateProjectOptions, ProjectConfig } from "./types.js";
import { stringifyYaml } from "./yaml.js";

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

async function seedProjectDirectories(projectRoot: string): Promise<void> {
  for (const dir of STEP_DIRS) {
    await fs.ensureDir(path.join(projectRoot, dir));
  }
  for (const file of STEP6_FILES) {
    await fs.ensureFile(path.join(projectRoot, "06_execution_plan", file));
  }
}

async function writeProjectConfig(projectRoot: string, options: CreateProjectOptions): Promise<void> {
  const config: ProjectConfig = {
    pack: options.pack,
    ide: options.ide,
    platforms: {
      image: { default: options.imagePlatform },
      video: { default: options.videoPlatform }
    },
    workflow: {
      enhanced_flow: {
        enabled: true
      }
    }
  };
  await fs.writeFile(path.join(projectRoot, "project.config.yaml"), stringifyYaml(config), "utf8");
}

async function seedStarterFiles(repoRoot: string, projectRoot: string): Promise<void> {
  const starterRoot = path.join(repoRoot, "packs", "official-ai-video", "starters", "solo-director-project");
  await copyDirectory(starterRoot, projectRoot);
}

export async function createProject(options: CreateProjectOptions): Promise<void> {
  const projectName = validateSafeDirectoryName(options.projectName, "Project name");
  const projectRoot = path.join(options.targetRoot, projectName);
  const repoRoot = resolveRepoRoot(moduleDir);
  await fs.ensureDir(projectRoot);
  await seedStarterFiles(repoRoot, projectRoot);
  await seedProjectDirectories(projectRoot);
  await writeProjectConfig(projectRoot, options);
  await fs.writeFile(
    path.join(projectRoot, "README.md"),
    `# ${projectName}\n\nGenerated by ai-video-workflow.\n`,
    "utf8"
  );
  await syncProject({
    repoRoot,
    projectRoot,
    ide: options.ide,
    pack: options.pack
  });
}
