import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { STEP6_FILES, STEP_DIRS } from "./constants.js";
import { copyDirectory, writeFileIfMissing } from "./fs-utils.js";
import { validateSafeDirectoryName } from "./name-validation.js";
import { resolveRepoRoot } from "./paths.js";
import { assertCanInitializeProject } from "./project-root.js";
import { syncProject } from "./sync.js";
import type { CreateProjectOptions, ProjectConfig } from "./types.js";
import { stringifyYaml } from "./yaml.js";

const moduleDir = path.dirname(fileURLToPath(import.meta.url));

async function seedProjectDirectories(repoRoot: string, projectRoot: string): Promise<void> {
  for (const dir of STEP_DIRS) {
    await fs.ensureDir(path.join(projectRoot, dir));
  }
  await writeFileIfMissing(
    path.join(projectRoot, "01_concept", "story-kernel.md"),
    await fs.readFile(path.join(repoRoot, "packs", "official-ai-video", "templates", "01_concept", "story-kernel.md"), "utf8")
  );
  for (const file of STEP6_FILES) {
    await writeFileIfMissing(
      path.join(projectRoot, "06_execution_plan", file),
      await fs.readFile(path.join(repoRoot, "packs", "official-ai-video", "templates", "06_execution_plan", file), "utf8")
    );
  }
}

async function writeProjectConfig(projectRoot: string, options: CreateProjectOptions): Promise<void> {
  const config: ProjectConfig = {
    pack: options.pack,
    ide: options.ide,
    platforms: {
      image: { default: options.imagePlatform },
      video: { default: options.videoPlatform }
    },
    workflow: {
      enhanced_flow: {
        enabled: true
      }
    }
  };
  await fs.writeFile(path.join(projectRoot, "project.config.yaml"), stringifyYaml(config), "utf8");
}

async function seedStarterFiles(repoRoot: string, projectRoot: string): Promise<void> {
  const starterRoot = path.join(repoRoot, "packs", "official-ai-video", "starters", "solo-director-project");
  await copyDirectory(starterRoot, projectRoot);
}

function renderProjectReadme(projectName: string, ide: string): string {
  return [
    `# ${projectName}`,
    "",
    "This is an AI video creative project generated by `ai-video-workflow`. It is not the `ai-video-workflow` tool repository.",
    "",
    "## Start Here",
    "",
    "1. Open this project directory in your AI agent.",
    "2. Ask the agent to read `AGENTS.md` and `docs/ai-workspace/README.md` first.",
    "3. Start creative planning in `01_concept/story-kernel.md`.",
    "4. Keep Step 1 to Step 6 files as the source of truth.",
    "",
    "## Useful Commands",
    "",
    "```powershell",
    `ai-video-workflow verify --project . --ide ${ide}`,
    "ai-video-workflow export-obsidian --project . --in-project-view",
    "ai-video-workflow verify-obsidian --project . --in-project-view",
    "```",
    "",
    "## Obsidian Boundary",
    "",
    "If you use Obsidian, open `_views/obsidian/` as the vault. Do not open this project root itself as the Obsidian vault.",
    "",
    "External vault mode is still available with `ai-video-workflow export-obsidian --project . --out <vault-path>`.",
    ""
  ].join("\n");
}

export function renderInitNextSteps({
  projectName,
  projectRoot,
  ide
}: {
  projectName: string;
  projectRoot: string;
  ide: string;
}): string {
  const quotedProjectRoot = projectRoot.includes(" ") ? `"${projectRoot}"` : projectRoot;
  return [
    `Created ${projectName}`,
    `Project path: ${projectRoot}`,
    "",
    "Open this directory in your AI agent:",
    projectRoot,
    "",
    "Copy this first prompt to the agent:",
    "I want to work on this ai-video-workflow creative project. Please read AGENTS.md and docs/ai-workspace/README.md first, then help me start from 01_concept/story-kernel.md. Do not treat _views/obsidian or IDE runtime mirrors as source files.",
    "",
    "Verify the project:",
    `ai-video-workflow verify --project ${quotedProjectRoot} --ide ${ide}`,
    "",
    "Optional Obsidian viewing layer:",
    `ai-video-workflow export-obsidian --project ${quotedProjectRoot} --in-project-view`,
    `ai-video-workflow verify-obsidian --project ${quotedProjectRoot} --in-project-view`
  ].join("\n");
}

export async function createProject(options: CreateProjectOptions): Promise<string> {
  const projectName = validateSafeDirectoryName(options.projectName, "Project name");
  const projectRoot = await assertCanInitializeProject(options.targetRoot, projectName);
  const repoRoot = resolveRepoRoot(moduleDir);
  await fs.ensureDir(projectRoot);
  await seedStarterFiles(repoRoot, projectRoot);
  await seedProjectDirectories(repoRoot, projectRoot);
  await writeProjectConfig(projectRoot, options);
  await fs.writeFile(path.join(projectRoot, "README.md"), renderProjectReadme(projectName, options.ide), "utf8");
  await syncProject({
    repoRoot,
    projectRoot,
    ide: options.ide,
    pack: options.pack
  });
  return projectRoot;
}
